services:
  db:
    image: postgres:17
    container_name: "${GIT_OWNER}_postgres_db"

    env_file:
      - .env

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_db
      GIT_OWNER: ${GIT_OWNER}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: